---

version: "3.8"

services:

  valkey:
    image: valkey/valkey:latest
    container_name: valkey-standalone
    ports:
      - 6379:6379
    entrypoint: "/usr/local/bin/docker-entrypoint.sh --enable-debug-command yes --enable-module-command yes"
    profiles:
      - standalone
      - sentinel
      - replica
      - all

  replica:
    image: valkey/valkey:latest
    container_name: valkey-replica
    depends_on:
      - valkey
    entrypoint: "/usr/local/bin/docker-entrypoint.sh --replicaof valkey 6379"
    ports:
      - 6380:6379
    profiles:
      - replica
      - all

  cluster:
    container_name: valkey-cluster
    build:
      context: .
      dockerfile: dockers/Dockerfile.cluster
    ports:
      - 16379:16379
      - 16380:16380
      - 16381:16381
      - 16382:16382
      - 16383:16383
      - 16384:16384
    volumes:
      - "./dockers/cluster.valkey.conf:/valkey.conf:ro"
    profiles:
      - cluster
      - all

  stunnel:
    build:
      context: ./dockers/stunnel
    depends_on:
      - valkey
    ports:
      - "6666:6666"
    profiles:
      - all
      - standalone
      - ssl
    volumes:
      - "./dockers/stunnel/conf:/etc/stunnel/conf.d:ro"
      - "./dockers/stunnel/keys:/etc/stunnel/keys:ro"

  sentinel:
    image: valkey/valkey:latest
    container_name: valkey-sentinel
    depends_on:
      - valkey
    entrypoint: "/usr/local/bin/valkey-sentinel /valkey.conf --port 26379"
    ports:
      - 26379:26379
    volumes:
      - "./dockers/sentinel.conf:/valkey.conf"
    profiles:
      - sentinel
      - all

  sentinel2:
    image: valkey/valkey:latest
    container_name: valkey-sentinel2
    depends_on:
      - valkey
    entrypoint: "/usr/local/bin/valkey-sentinel /valkey.conf --port 26380"
    ports:
      - 26380:26380
    volumes:
      - "./dockers/sentinel.conf:/valkey.conf"
    profiles:
      - sentinel
      - all

  sentinel3:
    image: valkey/valkey:latest
    container_name: valkey-sentinel3
    depends_on:
      - valkey
    entrypoint: "/usr/local/bin/valkey-sentinel /valkey.conf --port 26381"
    ports:
      - 26381:26381
    volumes:
      - "./dockers/sentinel.conf:/valkey.conf"
    profiles:
      - sentinel
      - all
